### ISSUE TITLE
Posts are NOT being made

### ISSUE THREAD

**Issue by JustenG** [Glarity/reddit2instagrambot#15] opened 2020-02-04 04:47 UTC
The MP4's and JPG's are being collected and downloaded correctly

After that I get the following;
>Request return 429 error!
>{'message': 'Please wait a few minutes before you try again.', 'status': 'fail'}
>Request return 405 error!
>{'message': '', 'status': 'fail'}
>Request return 404 error!
>Login success!

Does this have anything to do with the uploads not working?

It then proceeds to print out that the uploads were successful.
But no posts are added to my account.

Really confused as to why this isn't working, is there a major issue with the InstagramAPI?

**Comment by tylerolson** [comment] 2020-02-11 04:05
Duplicate of #14 
Instagram appeared to have finally ended support for their legacy API. I can't really do much about it but I will eventually migrate to a more permanent solution using Selenium.

**Closed as completed by tylerolson** 2020-02-11 04:05 UTC
